/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package reportes;

import config.Conexion;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author luisi
 */
public class RVentasDia extends javax.swing.JDialog {

     DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
     LocalDate localDate = LocalDate.now();
     String dateFor = localDate.format(formatter);
    
    /**
     * Creates new form NewJDialog
     */
    public RVentasDia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/gastroServerIcon.png")).getImage());
        jForDateofmeal.setText(dateFor.toString());
        jButton1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jForDateofmeal = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 58, 145));

        jLabel1.setFont(new java.awt.Font("Calling Heart", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Ventas por dia ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jForDateofmeal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jForDateofmeal.setToolTipText("Año-Mes-Dia");
        jForDateofmeal.setNextFocusableComponent(jButton1);
        jForDateofmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jForDateofmealActionPerformed(evt);
            }
        });
        jForDateofmeal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jForDateofmealKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jForDateofmealKeyReleased(evt);
            }
        });

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jForDateofmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jForDateofmeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jForDateofmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jForDateofmealActionPerformed
        // TODO add your handling code here:
        // Verificamos si la tecla presionada es "Enter"
    }//GEN-LAST:event_jForDateofmealActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        generarReporteMeals();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jForDateofmealKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jForDateofmealKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jForDateofmealKeyPressed

    private void jForDateofmealKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jForDateofmealKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jForDateofmealKeyReleased

    public void generarReporteMeals() {
    try {
        Conexion cn = new Conexion();
        Connection con;
        Statement st;
        ResultSet rs;
        String sqlDatetime = jForDateofmeal.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateFormat.parse(sqlDatetime);
        java.sql.Date dateSql = new java.sql.Date(date.getTime());
        String archivo = "ReporteDeMeals" + dateSql + ".html";

        FileWriter arch = new FileWriter(archivo);
        arch.write("<!DOCTYPE html>");
        arch.write("<html lang=\"en\">");
        arch.write("<head>");
        arch.write("<meta charset=\"UTF-8\">");
        arch.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        arch.write("<title>Reporte de Meals</title>");
        arch.write("<style>");
        arch.write("body {font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #DEF7F4;}");
        arch.write(".container {max-width: 800px; margin: 20px auto; padding: 20px; background-color: #fafbfb; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);}");
        arch.write("h1 {text-align: center; color: #333;}");
        arch.write("table {width: 100%; border-collapse: collapse; margin-bottom: 20px;}");
        arch.write("th, td {padding: 8px; text-align: left; border-bottom: 1px solid #ddd;}");
        arch.write("th {background-color: #f2f2f2;}");
        arch.write(".total {margin-top: 20px; text-align: right; font-weight: bold;}");
        arch.write("</style>");
        arch.write("</head>");
        arch.write("<body>");
        arch.write("<div class=\"container\">");
        arch.write("<h1>REPORTE DE VENTA</h1>");
        arch.write("<p>FECHA DEL REPORTE: " + dateSql + "</p>");
        arch.write("<table>");
        arch.write("<thead>");
        arch.write("<tr>");
        arch.write("<th>id</th>");
        arch.write("<th>date_of_meal</th>");
        arch.write("<th>cost_of_meal</th>");
        arch.write("<th>customers_name</th>");
        arch.write("<th>staff_first_name</th>");
        arch.write("<th>staff_last_name</th>");
        arch.write("</tr>");
        arch.write("</thead>");
        arch.write("<tbody>");

        String sql = "SELECT sales.id, sales.date_of_meal, sales.amount, customers.name, staff.first_name,staff.last_name FROM sales,customers,staff WHERE date_of_meal='" + dateSql + "' AND staff.id=id_staff AND customers.id=id_customer ORDER BY id;";
        con = cn.getConnection();
        st = con.createStatement();
        rs = st.executeQuery(sql);

        int cont = 0;
        double sum = 0;
        while (rs.next()) {
            arch.write("<tr>");
            arch.write("<td>" + rs.getString(1) + "</td>");
            arch.write("<td>" + rs.getString(2) + "</td>");
            arch.write("<td>$" + rs.getString(3) + "</td>");
            arch.write("<td>" + rs.getString(4) + "</td>");
            arch.write("<td>" + rs.getString(5) + "</td>");
            arch.write("<td>" + rs.getString(6) + "</td>");
            arch.write("</tr>");
            cont++;
            sum += Double.parseDouble(rs.getString(3));
        }

        arch.write("</tbody>");
        arch.write("</table>");
        arch.write("<p class=\"total\">TOTAL DE INGRESOS: $" + sum + "</p>");
        arch.write("<p class=\"total\">TOTAL DE VENTAS REALIZADAS: " + cont + "</p>");
        arch.write("</div>");
        arch.write("</body>");
        arch.write("</html>");
        arch.close();

        // Abre el archivo con el navegador predeterminado
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + archivo);

    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RVentasDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RVentasDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RVentasDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RVentasDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RVentasDia dialog = new RVentasDia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jForDateofmeal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
